In [34]:
import numpy as np

MLP = (5,3,2,2)
x0 = np.matrix('1; 1; 1; 1; 1')
t = np.matrix('1; -1')
learning_rate = 0.1

# Initialize weights
W1 = np.matrix([[1,1,1,1,1],[0,0,0,0,0],[1,1,1,1,1]])
W2 = np.matrix([[1,1,1],[1,1,1]])
W3 = np.matrix([[0,0],[0,0]])

# Initialize biases
b1 = np.matrix('1; 1; 1')
b2 = np.matrix('1; 1')
b3 = np.matrix('0; 0')

# Forward Propagation
z1 = np.add(np.matmul(W1, x0), b1)
x1 = np.tanh(z1)

z2 = np.add(np.matmul(W2, x1), b2)
x2 = np.tanh(z2)

z3 = np.add(np.matmul(W3, x2), b3)
x3 = np.tanh(z3)

# Calculate deltas
d3 = np.multiply(x3 - t, 1 - np.square(np.tanh(z3)))
d2 = np.multiply(np.matmul(W3.T, d3), (1 - np.square(np.tanh(z2))))
d1 = np.multiply(np.matmul(W2.T, d2), (1 - np.square(np.tanh(z1))))

# Calculate new weights and biases
dE_dW1 = np.matmul(d1, x0.T)
W1_new = W1 - learning_rate * dE_dW1
dE_db1 = d1
b1_new = b1 - learning_rate * dE_db1

dE_dW2 = np.matmul(d2, x1.T)
W2_new = W2 - learning_rate * dE_dW2
dE_db2 = d2
b2_new = b2 - learning_rate * dE_db2

dE_dW3 = np.matmul(d3, x2.T)
W3_new = W3 - learning_rate * dE_dW3
dE_db3 = d3
b3_new = b3 - learning_rate * dE_db3

# Prints
print(W1_new)
print(b1_new)

print(W2_new)
print(b2_new)

print(W3_new)
print(b3_new)

[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]
[[1.]
 [1.]
 [1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1.]
 [1.]]
[[ 0.09989197  0.09989197]
 [-0.09989197 -0.09989197]]
[[ 0.1]
 [-0.1]]
