In [6]:
import numpy as np

def activation(x):
    return np.tanh(x)
    
def activation_ddx(x):
    return 1 - np.square(np.tanh(x))

MLP = (5,3,2,2)
x0 = np.matrix('1; 1; 1; 1; 1')
t = np.matrix('1; -1')
learning_rate = 0.1

# Initialize weights
W1 = np.matrix([[1,1,1,1,1],[0,0,0,0,0],[1,1,1,1,1]])
W2 = np.matrix([[1,1,1],[1,1,1]])
W3 = np.matrix([[0,0],[0,0]])

# Initialize biases
b1 = np.matrix('1; 1; 1')
b2 = np.matrix('1; 1')
b3 = np.matrix('0; 0')

# Forward Propagation
z1 = np.add(np.matmul(W1, x0), b1)
x1 = activation(z1)

z2 = np.add(np.matmul(W2, x1), b2)
x2 = activation(z2)

z3 = np.add(np.matmul(W3, x2), b3)
x3 = activation(z3)
#print("z1", z1)
#print("x1", x1)
#print("z2", z2)
#print("x2", x2)
#print("z3", z3)
#print("x3", x3)

# Calculate deltas
dE_dx3 = x3 - t
d3 = np.multiply(dE_dx3, activation_ddx(z3))
d2 = np.multiply(np.matmul(W3.T, d3), activation_ddx(z2))
d1 = np.multiply(np.matmul(W2.T, d2), activation_ddx(z1))
#print(np.square(np.tanh(z3)))
#print(np.square(np.tanh(z2)))
#print(np.square(np.tanh(z1)))
#print(d3)
#print(d2)
#print(d1)

# Calculate new weights and biases
dE_dW1 = np.matmul(d1, x0.T)
W1_new = W1 - learning_rate * dE_dW1
dE_db1 = d1
b1_new = b1 - learning_rate * dE_db1

dE_dW2 = np.matmul(d2, x1.T)
W2_new = W2 - learning_rate * dE_dW2
dE_db2 = d2
b2_new = b2 - learning_rate * dE_db2

dE_dW3 = np.matmul(d3, x2.T)
W3_new = W3 - learning_rate * dE_dW3
dE_db3 = d3
b3_new = b3 - learning_rate * dE_db3

# Prints
print(W1_new)
print(b1_new)

print(W2_new)
print(b2_new)

print(W3_new)
print(b3_new)

[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]
[[1.]
 [1.]
 [1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1.]
 [1.]]
[[ 0.09989197  0.09989197]
 [-0.09989197 -0.09989197]]
[[ 0.1]
 [-0.1]]


In [10]:
import numpy as np
from scipy.special import softmax 

def activation(x):
    return np.tanh(x)
    
def activation_ddx(x):
    return 1 - np.square(np.tanh(x))

def activation_out(x):
    return softmax(x)
    
def activation_out_ddx(x):
    return np.multiply(softmax(x),1-softmax(x))

MLP = (5,3,2,2)
x0 = np.matrix('1; 1; 1; 1; 1')
t = np.matrix('1; 0')
learning_rate = 0.1

# Initialize weights
W1 = np.matrix([[1,1,1,1,1],[0,0,0,0,0],[1,1,1,1,1]])
W2 = np.matrix([[1,1,1],[1,1,1]])
W3 = np.matrix([[0,0],[0,0]])

# Initialize biases
b1 = np.matrix('1; 1; 1')
b2 = np.matrix('1; 1')
b3 = np.matrix('0; 0')

# Forward Propagation
z1 = np.add(np.matmul(W1, x0), b1)
x1 = activation(z1)

z2 = np.add(np.matmul(W2, x1), b2)
x2 = activation(z2)

z3 = np.add(np.matmul(W3, x2), b3)
x3 = activation_out(z3)
#print("z1", z1)
#print("x1", x1)
#print("z2", z2)
#print("x2", x2)
#print("z3", z3)
#print("x3", x3)

# Calculate deltas
dE_dx3 = x3 - t
d3 = dE_dx3
d2 = np.multiply(np.matmul(W3.T, d3), activation_ddx(z2))
d1 = np.multiply(np.matmul(W2.T, d2), activation_ddx(z1))
#print(np.square(np.tanh(z2)))
#print(np.square(np.tanh(z1)))
#print(d3)
#print(d2)
#print(d1)

# Calculate new weights and biases
dE_dW1 = np.matmul(d1, x0.T)
W1_new = W1 - learning_rate * dE_dW1
dE_db1 = d1
b1_new = b1 - learning_rate * dE_db1

dE_dW2 = np.matmul(d2, x1.T)
W2_new = W2 - learning_rate * dE_dW2
dE_db2 = d2
b2_new = b2 - learning_rate * dE_db2

dE_dW3 = np.matmul(d3, x2.T)
W3_new = W3 - learning_rate * dE_dW3
dE_db3 = d3
b3_new = b3 - learning_rate * dE_db3

# Prints
print(W1_new)
print(b1_new)

print(W2_new)
print(b2_new)

print(W3_new)
print(b3_new)

[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]
[[1.]
 [1.]
 [1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1.]
 [1.]]
[[ 0.04994599  0.04994599]
 [-0.04994599 -0.04994599]]
[[ 0.05]
 [-0.05]]


In [8]:
import numpy as np
from scipy.special import softmax 

def activation(x):
    return np.tanh(x)
    
def activation_ddx(x):
    return 1 - np.square(np.tanh(x))

def activation_out(x):
    return softmax(x)
    
def activation_out_ddx(x):
    return np.multiply(softmax(x),1-softmax(x))

MLP = (5,3,2,2)
x0 = np.matrix('1; 0; 1; 0')
t = np.matrix('0; 1; 0')
learning_rate = 0.1

# Initialize weights
W1 = np.matrix([[0.1,0.1,0.1,0.1],[0.1,0.1,0.1,0.1],[0.1,0.1,0.1,0.1],[0.1,0.1,0.1,0.1]])
W2 = np.matrix([[0.1,0.1,0.1,0.1],[0.1,0.1,0.1,0.1],[0.1,0.1,0.1,0.1]])
W3 = np.matrix([[0.1,0.1,0.1],[0.1,0.1,0.1],[0.1,0.1,0.1]])

# Initialize biases
b1 = np.matrix('0.1; 0.1; 0.1; 0.1')
b2 = np.matrix('0.1; 0.1; 0.1')
b3 = np.matrix('0.1; 0.1; 0.1')

# Forward Propagation
z1 = np.add(np.matmul(W1, x0), b1)
x1 = activation(z1)

z2 = np.add(np.matmul(W2, x1), b2)
x2 = activation(z2)

z3 = np.add(np.matmul(W3, x2), b3)
x3 = activation_out(z3)

# Calculate deltas
dE_dx3 = x3 - t
d3 = dE_dx3
d2 = np.multiply(np.matmul(W3.T, d3), activation_ddx(z2))
d1 = np.multiply(np.matmul(W2.T, d2), activation_ddx(z1))

# Calculate new weights and biases
dE_dW1 = np.matmul(d1, x0.T)
W1_new = W1 - learning_rate * dE_dW1
dE_db1 = d1
b1_new = b1 - learning_rate * dE_db1

dE_dW2 = np.matmul(d2, x1.T)
W2_new = W2 - learning_rate * dE_dW2
dE_db2 = d2
b2_new = b2 - learning_rate * dE_db2

dE_dW3 = np.matmul(d3, x2.T)
W3_new = W3 - learning_rate * dE_dW3
dE_db3 = d3
b3_new = b3 - learning_rate * dE_db3

# Prints
print(W1_new)
print(b1_new)

print(W2_new)
print(b2_new)

print(W3_new)
print(b3_new)

[[0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]]
[[0.1]
 [0.1]
 [0.1]
 [0.1]]
[[0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]]
[[0.1]
 [0.1]
 [0.1]]
[[0.09289322 0.09289322 0.09289322]
 [0.11421357 0.11421357 0.11421357]
 [0.09289322 0.09289322 0.09289322]]
[[0.06666667]
 [0.16666667]
 [0.06666667]]
